// This file was automatically generated.  Do not modify.

"use strict";

goog.provide("Blockly.ScratchMsgs.allLocales");

goog.require("Blockly.ScratchMsgs");

Blockly.ScratchMsgs.locales["en"] = {
  CONTROL_FOREVER: "forever",
  CONTROL_REPEAT: "repeat %1",
  CONTROL_IF: "if %1 then",
  CONTROL_ELSE: "else",
  CONTROL_STOP: "stop",
  CONTROL_STOP_ALL: "all",
  CONTROL_STOP_THIS: "this script",
  CONTROL_STOP_OTHER: "other scripts in sprite",
  CONTROL_WAIT: "wait %1 seconds",
  CONTROL_WAITUNTIL: "wait until %1",
  CONTROL_REPEATUNTIL: "repeat until %1",
  CONTROL_WHILE: "while %1",
  CONTROL_FOREACH: "for each %1 in %2",
  CONTROL_STARTASCLONE: "when I start as a clone",
  CONTROL_CREATECLONEOF: "create clone of %1",
  CONTROL_CREATECLONEOF_MYSELF: "myself",
  CONTROL_DELETETHISCLONE: "delete this clone",
  CONTROL_COUNTER: "counter",
  CONTROL_INCRCOUNTER: "increment counter",
  CONTROL_CLEARCOUNTER: "clear counter",
  CONTROL_ALLATONCE: "all at once",
  DATA_SETVARIABLETO: "set %1 to %2",
  DATA_CHANGEVARIABLEBY: "change %1 by %2",
  DATA_SHOWVARIABLE: "show variable %1",
  DATA_HIDEVARIABLE: "hide variable %1",
  DATA_ADDTOLIST: "add %1 to %2",
  DATA_DELETEOFLIST: "delete %1 of %2",
  DATA_DELETEALLOFLIST: "delete all of %1",
  DATA_INSERTATLIST: "insert %1 at %2 of %3",
  DATA_REPLACEITEMOFLIST: "replace item %1 of %2 with %3",
  DATA_ITEMOFLIST: "item %1 of %2",
  DATA_ITEMNUMOFLIST: "item # of %1 in %2",
  DATA_LENGTHOFLIST: "length of %1",
  DATA_LISTCONTAINSITEM: "%1 contains %2?",
  DATA_SHOWLIST: "show list %1",
  DATA_HIDELIST: "hide list %1",
  DATA_INDEX_ALL: "all",
  DATA_INDEX_LAST: "last",
  DATA_INDEX_RANDOM: "random",
  EVENT_WHENARDUINOBEGIN: "when Arduino begin",
  EVENT_WHENMICROPYTHONBEGIN: "when MicroPython begin",
  EVENT_WHENMICROBITBEGIN: "when Microbit begin",
  EVENT_WHENMICROBITBUTTONPRESSED: "when button %1 pressed",
  EVENT_WHENMICROBITPINBEINGTOUCHED: "when pin %1 being touched",
  EVENT_WHENMICROBITGESTURE: "when the gestrue %1",
  EVENT_WHENFLAGCLICKED: "when %1 clicked",
  EVENT_WHENTHISSPRITECLICKED: "when this sprite clicked",
  EVENT_WHENSTAGECLICKED: "when stage clicked",
  EVENT_WHENTOUCHINGOBJECT: "when this sprite touches %1",
  EVENT_WHENBROADCASTRECEIVED: "when I receive %1",
  EVENT_WHENBACKDROPSWITCHESTO: "when backdrop switches to %1",
  EVENT_WHENGREATERTHAN: "when %1 > %2",
  EVENT_WHENGREATERTHAN_TIMER: "timer",
  EVENT_WHENGREATERTHAN_LOUDNESS: "loudness",
  EVENT_BROADCAST: "broadcast %1",
  EVENT_BROADCASTANDWAIT: "broadcast %1 and wait",
  EVENT_WHENKEYPRESSED: "when %1 key pressed",
  EVENT_WHENMICROBITGESTURE_SHAKEN: "shaken",
  EVENT_WHENMICROBITGESTURE_TILTEDUPWARD: "tilted upward",
  EVENT_WHENMICROBITGESTURE_TILTEDDOWNWARD: "tilted downward",
  EVENT_WHENMICROBITGESTURE_TILTEDDLEFTWARD: "tilted leftward",
  EVENT_WHENMICROBITGESTURE_TILTEDDRIGHTWARD: "tilted rightward",
  EVENT_WHENMICROBITGESTURE_FACEUP: "face up",
  EVENT_WHENMICROBITGESTURE_FACEDOWN: "face down",
  EVENT_WHENMICROBITGESTURE_FREEFALL: "freefall",
  EVENT_WHENKEYPRESSED_SPACE: "space",
  EVENT_WHENKEYPRESSED_LEFT: "left arrow",
  EVENT_WHENKEYPRESSED_RIGHT: "right arrow",
  EVENT_WHENKEYPRESSED_DOWN: "down arrow",
  EVENT_WHENKEYPRESSED_UP: "up arrow",
  EVENT_WHENKEYPRESSED_ANY: "any",
  LOOKS_SAYFORSECS: "say %1 for %2 seconds",
  LOOKS_SAY: "say %1 %2",
  LOOKS_HELLO: "Hello!",
  LOOKS_THINKFORSECS: "think %1 for %2 seconds",
  LOOKS_THINK: "think %1",
  LOOKS_HMM: "Hmm...",
  LOOKS_SHOW: "show %1",
  LOOKS_HIDE: "hide %1",
  LOOKS_HIDEALLSPRITES: "hide all sprites",
  LOOKS_EFFECT_COLOR: "color",
  LOOKS_EFFECT_FISHEYE: "fisheye",
  LOOKS_EFFECT_WHIRL: "whirl",
  LOOKS_EFFECT_PIXELATE: "pixelate",
  LOOKS_EFFECT_MOSAIC: "mosaic",
  LOOKS_EFFECT_BRIGHTNESS: "brightness",
  LOOKS_EFFECT_GHOST: "ghost",
  LOOKS_CHANGEEFFECTBY: "change %1 effect by %2",
  LOOKS_SETEFFECTTO: "set %1 effect to %2",
  LOOKS_CLEARGRAPHICEFFECTS: "clear graphic effects",
  LOOKS_CHANGESIZEBY: "change size by %1",
  "LOOKS_GROW=": "1 by %2",
  LOOKS_SHIRINK: "shrink %1 by %2",
  LOOKS_RESETSIZE: "reset size %1",
  LOOKS_SETSIZETO: "set size to %1 %",
  LOOKS_SIZE: "size",
  LOOKS_CHANGESTRETCHBY: "change stretch by %1",
  LOOKS_SETSTRETCHTO: "set stretch to %1 %",
  LOOKS_SWITCHCOSTUMETO: "switch costume to %1",
  LOOKS_NEXTCOSTUME: "next costume",
  LOOKS_SWITCHBACKDROPTO: "switch backdrop to %1",
  LOOKS_GOTOFRONTBACK: "go to %1 layer",
  LOOKS_GOTOFRONTBACK_FRONT: "front",
  LOOKS_GOTOFRONTBACK_BACK: "back",
  LOOKS_GOFORWARDBACKWARDLAYERS: "go %1 %2 layers",
  LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD: "forward",
  LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD: "backward",
  LOOKS_BACKDROPNUMBERNAME: "backdrop %1",
  LOOKS_COSTUMENUMBERNAME: "costume %1",
  LOOKS_NUMBERNAME_NUMBER: "number",
  LOOKS_NUMBERNAME_NAME: "name",
  LOOKS_SWITCHBACKDROPTOANDWAIT: "switch backdrop to %1 and wait",
  LOOKS_NEXTBACKDROP_BLOCK: "next backdrop",
  LOOKS_NEXTBACKDROP: "next backdrop",
  LOOKS_PREVIOUSBACKDROP: "previous backdrop",
  LOOKS_RANDOMBACKDROP: "random backdrop",
  MOTION_MOVESTEPS: "move %1 steps",
  MOTION_MOVESRIGHT: "move right %1 %2 steps",
  MOTION_MOVESLEFT: "move left %1 %2 steps",
  MOTION_MOVESUP: "move up %1 %2 steps",
  MOTION_MOVESDOWN: "move down %1 %2 steps",
  MOTION_HOP: "hop %1 %2 steps",
  MOTION_GO_HOME: "go %1 home",
  MOTION_TURNLEFT: "turn %1 %2 degrees",
  MOTION_TURNRIGHT: "turn %1 %2 degrees",
  MOTION_POINTINDIRECTION: "point in direction %1",
  MOTION_POINTTOWARDS: "point towards %1",
  MOTION_POINTTOWARDS_POINTER: "mouse-pointer",
  MOTION_POINTTOWARDS_RANDOM: "random direction",
  MOTION_GOTO: "go to %1",
  MOTION_GOTO_POINTER: "mouse-pointer",
  MOTION_GOTO_RANDOM: "random position",
  MOTION_GOTOXY: "go to x: %1 y: %2",
  MOTION_GLIDESECSTOXY: "glide %1 secs to x: %2 y: %3",
  MOTION_GLIDETO: "glide %1 secs to %2",
  MOTION_GLIDETO_POINTER: "mouse-pointer",
  MOTION_GLIDETO_RANDOM: "random position",
  MOTION_CHANGEXBY: "change x by %1",
  MOTION_SETX: "set x to %1",
  MOTION_CHANGEYBY: "change y by %1",
  MOTION_SETY: "set y to %1",
  MOTION_IFONEDGEBOUNCE: "if on edge, bounce",
  MOTION_SETROTATIONSTYLE: "set rotation style %1",
  MOTION_SETROTATIONSTYLE_LEFTRIGHT: "left-right",
  MOTION_SETROTATIONSTYLE_DONTROTATE: "dont rotate",
  MOTION_SETROTATIONSTYLE_ALLAROUND: "all around",
  MOTION_XPOSITION: "x position",
  MOTION_YPOSITION: "y position",
  MOTION_DIRECTION: "direction",
  MOTION_SCROLLRIGHT: "scroll right %1",
  MOTION_SCROLLUP: "scroll up %1",
  MOTION_ALIGNSCENE: "align scene %1",
  MOTION_ALIGNSCENE_BOTTOMLEFT: "bottom-left",
  MOTION_ALIGNSCENE_BOTTOMRIGHT: "bottom-right",
  MOTION_ALIGNSCENE_MIDDLE: "middle",
  MOTION_ALIGNSCENE_TOPLEFT: "top-left",
  MOTION_ALIGNSCENE_TOPRIGHT: "top-right",
  MOTION_XSCROLL: "x scroll",
  MOTION_YSCROLL: "y scroll",
  MOTION_STAGE_SELECTED: "Stage selected: no motion blocks",
  OPERATORS_ADD: "%1 + %2",
  OPERATORS_SUBTRACT: "%1 - %2",
  OPERATORS_MULTIPLY: "%1 * %2",
  OPERATORS_DIVIDE: "%1 / %2",
  OPERATORS_RANDOM: "pick random %1 to %2",
  OPERATORS_GT: "%1 > %2",
  OPERATORS_LT: "%1 < %2",
  OPERATORS_EQUALS: "%1 = %2",
  OPERATORS_AND: "%1 and %2",
  OPERATORS_OR: "%1 or %2",
  OPERATORS_NOT: "not %1",
  OPERATORS_JOIN: "join %1 %2",
  OPERATORS_JOIN_APPLE: "apple",
  OPERATORS_JOIN_BANANA: "banana",
  OPERATORS_LETTEROF: "letter %1 of %2",
  OPERATORS_LETTEROF_APPLE: "a",
  OPERATORS_LENGTH: "length of %1",
  OPERATORS_CONTAINS: "%1 contains %2?",
  OPERATORS_MOD: "%1 mod %2",
  OPERATORS_ROUND: "round %1",
  OPERATORS_MATHOP: "%1 of %2",
  OPERATORS_MATHOP_ABS: "abs",
  OPERATORS_MATHOP_FLOOR: "floor",
  OPERATORS_MATHOP_CEILING: "ceiling",
  OPERATORS_MATHOP_SQRT: "sqrt",
  OPERATORS_MATHOP_SIN: "sin",
  OPERATORS_MATHOP_COS: "cos",
  OPERATORS_MATHOP_TAN: "tan",
  OPERATORS_MATHOP_ASIN: "asin",
  OPERATORS_MATHOP_ACOS: "acos",
  OPERATORS_MATHOP_ATAN: "atan",
  OPERATORS_MATHOP_LN: "ln",
  OPERATORS_MATHOP_LOG: "log",
  OPERATORS_MATHOP_EEXP: "e ^",
  OPERATORS_MATHOP_10EXP: "10 ^",
  PROCEDURES_DEFINITION: "define %1",
  SENSING_TOUCHINGOBJECT: "touching %1?",
  SENSING_TOUCHINGOBJECT_POINTER: "mouse-pointer",
  SENSING_TOUCHINGOBJECT_EDGE: "edge",
  SENSING_TOUCHINGCOLOR: "touching color %1?",
  SENSING_COLORISTOUCHINGCOLOR: "color %1 is touching %2?",
  SENSING_DISTANCETO: "distance to %1",
  SENSING_DISTANCETO_POINTER: "mouse-pointer",
  SENSING_ASKANDWAIT: "ask %1 and wait",
  SENSING_ASK_TEXT: "Whats your name?",
  SENSING_ANSWER: "answer",
  SENSING_KEYPRESSED: "key %1 pressed?",
  SENSING_MOUSEDOWN: "mouse down?",
  SENSING_MOUSEX: "mouse x",
  SENSING_MOUSEY: "mouse y",
  SENSING_SETDRAGMODE: "set drag mode %1",
  SENSING_SETDRAGMODE_DRAGGABLE: "draggable",
  SENSING_SETDRAGMODE_NOTDRAGGABLE: "not draggable",
  SENSING_LOUDNESS: "loudness",
  SENSING_LOUD: "loud?",
  SENSING_TIMER: "timer",
  SENSING_RESETTIMER: "reset timer",
  SENSING_OF: "%1 of %2",
  SENSING_OF_XPOSITION: "x position",
  SENSING_OF_YPOSITION: "y position",
  SENSING_OF_DIRECTION: "direction",
  SENSING_OF_COSTUMENUMBER: "costume #",
  SENSING_OF_COSTUMENAME: "costume name",
  SENSING_OF_SIZE: "size",
  SENSING_OF_VOLUME: "volume",
  SENSING_OF_BACKDROPNUMBER: "backdrop #",
  SENSING_OF_BACKDROPNAME: "backdrop name",
  SENSING_OF_STAGE: "Stage",
  SENSING_CURRENT: "current %1",
  SENSING_CURRENT_YEAR: "year",
  SENSING_CURRENT_MONTH: "month",
  SENSING_CURRENT_DATE: "date",
  SENSING_CURRENT_DAYOFWEEK: "day of week",
  SENSING_CURRENT_HOUR: "hour",
  SENSING_CURRENT_MINUTE: "minute",
  SENSING_CURRENT_SECOND: "second",
  SENSING_DAYSSINCE2000: "days since 2000",
  SENSING_USERNAME: "username",
  SENSING_USERID: "user id",
  SOUND_PLAY: "start sound %1",
  SOUND_PLAYUNTILDONE: "play sound %1 until done",
  SOUND_STOPALLSOUNDS: "stop all sounds",
  SOUND_SETEFFECTO: "set %1 effect to %2",
  SOUND_CHANGEEFFECTBY: "change %1 effect by %2",
  SOUND_CLEAREFFECTS: "clear sound effects",
  SOUND_EFFECTS_PITCH: "pitch",
  SOUND_EFFECTS_PAN: "pan left/right",
  SOUND_CHANGEVOLUMEBY: "change volume by %1",
  SOUND_SETVOLUMETO: "set volume to %1%",
  SOUND_VOLUME: "volume",
  SOUND_RECORD: "record...",
  CATEGORY_MOTION: "Motion",
  CATEGORY_LOOKS: "Looks",
  CATEGORY_SOUND: "Sound",
  CATEGORY_EVENTS: "Events",
  CATEGORY_CONTROL: "Control",
  CATEGORY_SENSING: "Sensing",
  CATEGORY_OPERATORS: "Operators",
  CATEGORY_VARIABLES: "Variables",
  CATEGORY_MYBLOCKS: "My Blocks",
  COPY: "Copy",
  PASTE: "Paste",
  DUPLICATE: "Duplicate",
  DELETE: "Delete",
  ADD_COMMENT: "Add Comment",
  REMOVE_COMMENT: "Remove Comment",
  DELETE_BLOCK: "Delete Block",
  DELETE_X_BLOCKS: "Delete %1 Blocks",
  DELETE_ALL_BLOCKS: "Delete all %1 blocks?",
  CLEAN_UP: "Clean up Blocks",
  HELP: "Help",
  UNDO: "Undo",
  REDO: "Redo",
  EDIT_PROCEDURE: "Edit",
  SHOW_PROCEDURE_DEFINITION: "Go to definition",
  WORKSPACE_COMMENT_DEFAULT_TEXT: "Say something...",
  COLOUR_HUE_LABEL: "Color",
  COLOUR_SATURATION_LABEL: "Saturation",
  COLOUR_BRIGHTNESS_LABEL: "Brightness",
  CHANGE_VALUE_TITLE: "Change value:",
  RENAME_VARIABLE: "Rename variable",
  RENAME_VARIABLE_TITLE: 'Rename all "%1" variables to:',
  RENAME_VARIABLE_MODAL_TITLE: "Rename Variable",
  NEW_VARIABLE: "Make a Variable",
  NEW_VARIABLE_TITLE: "New variable name:",
  VARIABLE_MODAL_TITLE: "ariable",
  VARIABLE_ALREADY_EXISTS: 'ariable named "%1" already exists.',
  VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE:
    'ariable named "%1" already exists for another variable of type "%2".',
  DELETE_VARIABLE_CONFIRMATION: '1 uses of the "%2" variable?',
  CANNOT_DELETE_VARIABLE_PROCEDURE:
    'elete the variable "%1" because its part of the definition of the function "%2"',
  DELETE_VARIABLE: 'Delete the "%1" variable',
  NEW_PROCEDURE: "Make a Block",
  PROCEDURE_ALREADY_EXISTS: 'A procedure named "%1" already exists.',
  PROCEDURE_DEFAULT_NAME: "block name",
  PROCEDURE_USED:
    "elete a block definition, first remove all uses of the block",
  NEW_LIST: "Make a List",
  NEW_LIST_TITLE: "New list name:",
  LIST_MODAL_TITLE: "New List",
  LIST_ALREADY_EXISTS: 'A list named "%1" already exists.',
  RENAME_LIST_TITLE: 'Rename all "%1" lists to:',
  RENAME_LIST_MODAL_TITLE: "Rename List",
  DEFAULT_LIST_ITEM: "thing",
  DELETE_LIST: 'Delete the "%1" list',
  RENAME_LIST: "Rename list",
  NEW_BROADCAST_MESSAGE: "New message",
  NEW_BROADCAST_MESSAGE_TITLE: "New message name:",
  BROADCAST_MODAL_TITLE: "New Message",
  DEFAULT_BROADCAST_MESSAGE_NAME: "message1",
};

Blockly.ScratchMsgs.locales["id"] = {
  CONTROL_FOREVER: "selamanya",
  CONTROL_REPEAT: "ulangi %1 kali",
  CONTROL_IF: "jika %1",
  CONTROL_ELSE: "jika tidak",
  CONTROL_STOP: "berhenti",
  CONTROL_STOP_ALL: "semua",
  CONTROL_STOP_THIS: "skrip ini",
  CONTROL_STOP_OTHER: "skrip lain di sprite ini",
  CONTROL_WAIT: "tunggu %1 detik",
  CONTROL_WAITUNTIL: "tunggu sampai %1",
  CONTROL_REPEATUNTIL: "ulangi sampai %1",
  CONTROL_WHILE: "selama %1",
  CONTROL_FOREACH: "untuk setiap %1 dalam %2",
  CONTROL_STARTASCLONE: "ketika aku mulai sebagai clone",
  CONTROL_CREATECLONEOF: "buat clone dari %1",
  CONTROL_CREATECLONEOF_MYSELF: "diriku",
  CONTROL_DELETETHISCLONE: "hapus clone ini",
  CONTROL_COUNTER: "hitungan",
  CONTROL_INCRCOUNTER: "tingkatkan hitungan",
  CONTROL_CLEARCOUNTER: "bersihkan hitungan",
  CONTROL_ALLATONCE: "semuanya sekaligus",
  DATA_SETVARIABLETO: "atur %1 ke %2",
  DATA_CHANGEVARIABLEBY: "ubah %1 sebesar %2",
  DATA_SHOWVARIABLE: "tampilkan variabel %1",
  DATA_HIDEVARIABLE: "sembunyikan variabel %1",
  DATA_ADDTOLIST: "tambahkan %1 ke %2",
  DATA_DELETEOFLIST: "hapus %1 dari %2",
  DATA_DELETEALLOFLIST: "hapus semua dari %1",
  DATA_INSERTATLIST: "sisipkan %1 pada %2 dari %3",
  DATA_REPLACEITEMOFLIST: "ganti benda %1 dari %2 dengan %3",
  DATA_ITEMOFLIST: "benda %1 dari %2",
  DATA_ITEMNUMOFLIST: "benda # dari %1 di %2",
  DATA_LENGTHOFLIST: "panjang dari %1",
  DATA_LISTCONTAINSITEM: "%1 berisi %2?",
  DATA_SHOWLIST: "tampilkan daftar %1",
  DATA_HIDELIST: "sembunyikan daftar %1",
  DATA_INDEX_ALL: "semua",
  DATA_INDEX_LAST: "terakhir",
  DATA_INDEX_RANDOM: "sembarang",
  EVENT_WHENFLAGCLICKED: "ketika %1 diklik",
  EVENT_WHENTHISSPRITECLICKED: "ketika sprite ini diklik",
  EVENT_WHENSTAGECLICKED: "ketika panggung diklik",
  EVENT_WHENTOUCHINGOBJECT: "ketika sprite ini menyentuh %1",
  EVENT_WHENBROADCASTRECEIVED: "ketika aku menerima %1",
  EVENT_WHENBACKDROPSWITCHESTO: "ketika latar menjadi %1",
  EVENT_WHENGREATERTHAN: "ketika %1 > %2",
  EVENT_WHENGREATERTHAN_TIMER: "pengatur waktu",
  EVENT_WHENGREATERTHAN_LOUDNESS: "kenyaringan",
  EVENT_BROADCAST: "siarkan %1",
  EVENT_BROADCASTANDWAIT: "siarkan %1 dan tunggu",
  EVENT_WHENKEYPRESSED: "ketika tombol %1 ditekan",
  EVENT_WHENKEYPRESSED_SPACE: "spasi",
  EVENT_WHENKEYPRESSED_LEFT: "panah kiri",
  EVENT_WHENKEYPRESSED_RIGHT: "panah kanan",
  EVENT_WHENKEYPRESSED_DOWN: "panah bawah",
  EVENT_WHENKEYPRESSED_UP: "panah atas",
  EVENT_WHENKEYPRESSED_ANY: "manapun",
  LOOKS_SAYFORSECS: "katakan %1 selama %2 detik",
  LOOKS_SAY: "katakan %1 %2",
  LOOKS_GROW: "besar %1 %2",
  LOOKS_SHIRINK: "kecil %1 %2",
  LOOKS_RESETSIZE: "reset ukuran %1",
  LOOKS_HELLO: "Halo!",
  LOOKS_THINKFORSECS: "pikirkan %1 selama %2 detik",
  LOOKS_THINK: "pikirkan %1",
  LOOKS_HMM: "Hmm...",
  LOOKS_SHOW: "tampilkan %1",
  LOOKS_HIDE: "sembunyikan %1",
  LOOKS_HIDEALLSPRITES: "sembunyikan semua sprite",
  LOOKS_EFFECT_COLOR: "warna",
  LOOKS_EFFECT_FISHEYE: "mata ikan",
  LOOKS_EFFECT_WHIRL: "pusaran",
  LOOKS_EFFECT_PIXELATE: "pixelasi",
  LOOKS_EFFECT_MOSAIC: "mosaik",
  LOOKS_EFFECT_BRIGHTNESS: "kecerahan",
  LOOKS_EFFECT_GHOST: "bayangan",
  LOOKS_CHANGEEFFECTBY: "ubah efek %1 sebesar %2",
  LOOKS_SETEFFECTTO: "atur efek %1 ke %2",
  LOOKS_CLEARGRAPHICEFFECTS: "hapus semua efek grafis",
  LOOKS_CHANGESIZEBY: "ubah ukuran sebesar %1",
  LOOKS_SETSIZETO: "atur ukuran ke %1 %",
  LOOKS_SIZE: "ukuran",
  LOOKS_CHANGESTRETCHBY: "ubah rentangan sebesar %1",
  LOOKS_SETSTRETCHTO: "atur rentangan ke %1 %",
  LOOKS_SWITCHCOSTUMETO: "ganti kostum ke %1",
  LOOKS_NEXTCOSTUME: "kostum berikutnya",
  LOOKS_SWITCHBACKDROPTO: "ganti latar ke %1",
  LOOKS_GOTOFRONTBACK: "pergi ke lapisan %1",
  LOOKS_GOTOFRONTBACK_FRONT: "depan",
  LOOKS_GOTOFRONTBACK_BACK: "belakang",
  LOOKS_GOFORWARDBACKWARDLAYERS: "pergi %1 %2 lapisan",
  LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD: "maju",
  LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD: "mundur",
  LOOKS_BACKDROPNUMBERNAME: "latar %1",
  LOOKS_COSTUMENUMBERNAME: "%1 kostum",
  LOOKS_NUMBERNAME_NUMBER: "angka",
  LOOKS_NUMBERNAME_NAME: "nama",
  LOOKS_SWITCHBACKDROPTOANDWAIT: "ganti latar ke %1 dan tunggu",
  LOOKS_NEXTBACKDROP_BLOCK: "latar berikutnya",
  LOOKS_NEXTBACKDROP: "latar berikutnya",
  LOOKS_PREVIOUSBACKDROP: "latar sebelumnya",
  LOOKS_RANDOMBACKDROP: "latar sembarang",
  MOTION_MOVESTEPS: "gerak %1 langkah",
  MOTION_MOVESRIGHT: "gerak ke kanan %1 %2 langkah",
  MOTION_MOVESLEFT: "gerak ke kiri %1 %2 langkah",
  MOTION_MOVESUP: "gerak ke atas %1 %2 langkah",
  MOTION_MOVESDOWN: "gerak ke bawah %1 %2 langkah",
  MOTION_GO_HOME: "ke rumah %1",
  MOTION_HOP: "lompat %1 %2 kali",
  MOTION_TURNLEFT: "putar %1 %2 derajat",
  MOTION_TURNRIGHT: "putar %1 %2 derajat",
  MOTION_POINTINDIRECTION: "mengarah ke arah %1",
  MOTION_POINTTOWARDS: "mengarah ke %1",
  MOTION_POINTTOWARDS_POINTER: "pointer-mouse",
  MOTION_POINTTOWARDS_RANDOM: "arah sembarang",
  MOTION_GOTO: "pergi ke %1",
  MOTION_GOTO_POINTER: "pointer-mouse",
  MOTION_GOTO_RANDOM: "posisi sembarang",
  MOTION_GOTOXY: "pergi ke x: %1 y: %2",
  MOTION_GLIDESECSTOXY: "meluncur %1 detik ke x: %2 y: %3",
  MOTION_GLIDETO: "meluncur %1 detik ke %2",
  MOTION_GLIDETO_POINTER: "pointer-mouse",
  MOTION_GLIDETO_RANDOM: "posisi sembarang",
  MOTION_CHANGEXBY: "ubah x sebesar %1",
  MOTION_SETX: "atur x ke %1",
  MOTION_CHANGEYBY: "ubah y sebesar %1",
  MOTION_SETY: "atur y ke %1",
  MOTION_IFONEDGEBOUNCE: "jika di pinggir, pantulkan",
  MOTION_SETROTATIONSTYLE: "atur gaya rotasi %1",
  MOTION_SETROTATIONSTYLE_LEFTRIGHT: "kiri-kanan",
  MOTION_SETROTATIONSTYLE_DONTROTATE: "jangan berputar",
  MOTION_SETROTATIONSTYLE_ALLAROUND: "seluruh",
  MOTION_XPOSITION: "posisi x",
  MOTION_YPOSITION: "posisi y",
  MOTION_DIRECTION: "arah",
  MOTION_SCROLLRIGHT: "gulir ke kanan %1",
  MOTION_SCROLLUP: "gulir ke atas %1",
  MOTION_ALIGNSCENE: "luruskan pemandangan %1",
  MOTION_ALIGNSCENE_BOTTOMLEFT: "kiri-bawah",
  MOTION_ALIGNSCENE_BOTTOMRIGHT: "kanan-bawah",
  MOTION_ALIGNSCENE_MIDDLE: "tengah",
  MOTION_ALIGNSCENE_TOPLEFT: "kiri-atas",
  MOTION_ALIGNSCENE_TOPRIGHT: "kanan-atas",
  MOTION_XSCROLL: "guliran x",
  MOTION_YSCROLL: "guliran y",
  MOTION_STAGE_SELECTED: "Panggung terpilih: tidak ada balok gerakan",
  OPERATORS_ADD: "%1 + %2",
  OPERATORS_SUBTRACT: "%1 - %2",
  OPERATORS_MULTIPLY: "%1 * %2",
  OPERATORS_DIVIDE: "%1 / %2",
  OPERATORS_RANDOM: "pilih acak dari %1 hingga %2",
  OPERATORS_GT: "%1 > %2",
  OPERATORS_LT: "%1 < %2",
  OPERATORS_EQUALS: "%1 = %2",
  OPERATORS_AND: "%1 dan %2",
  OPERATORS_OR: "%1 atau %2",
  OPERATORS_NOT: "tidak %1",
  OPERATORS_JOIN: "gabungkan %1 %2",
  OPERATORS_JOIN_APPLE: "apel",
  OPERATORS_JOIN_BANANA: "pisang",
  OPERATORS_LETTEROF: "huruf %1 dari %2",
  OPERATORS_LETTEROF_APPLE: "a",
  OPERATORS_LENGTH: "panjang dari %1",
  OPERATORS_CONTAINS: "%1 berisi %2?",
  OPERATORS_MOD: "%1 mod %2",
  OPERATORS_ROUND: "bulatkan %1",
  OPERATORS_MATHOP: "%1 dari %2",
  OPERATORS_MATHOP_ABS: "abs",
  OPERATORS_MATHOP_FLOOR: "floor",
  OPERATORS_MATHOP_CEILING: "ceil",
  OPERATORS_MATHOP_SQRT: "akar kuadrat",
  OPERATORS_MATHOP_SIN: "sin",
  OPERATORS_MATHOP_COS: "cos",
  OPERATORS_MATHOP_TAN: "tan",
  OPERATORS_MATHOP_ASIN: "asin",
  OPERATORS_MATHOP_ACOS: "acos",
  OPERATORS_MATHOP_ATAN: "atan",
  OPERATORS_MATHOP_LN: "ln",
  OPERATORS_MATHOP_LOG: "log",
  OPERATORS_MATHOP_EEXP: "e ^",
  OPERATORS_MATHOP_10EXP: "10 ^",
  PROCEDURES_DEFINITION: "artikan %1",
  SENSING_TOUCHINGOBJECT: "menyentuh %1?",
  SENSING_TOUCHINGOBJECT_POINTER: "pointer-mouse",
  SENSING_TOUCHINGOBJECT_EDGE: "pinggir",
  SENSING_TOUCHINGCOLOR: "menyentuh warna %1?",
  SENSING_COLORISTOUCHINGCOLOR: "warna %1 menyentuh %2?",
  SENSING_DISTANCETO: "jarak dari %1",
  SENSING_DISTANCETO_POINTER: "pointer-mouse",
  SENSING_ASKANDWAIT: "tanya %1 dan tunggu",
  SENSING_ASK_TEXT: "Apa namamu?",
  SENSING_ANSWER: "jawaban",
  SENSING_KEYPRESSED: "tombol %1 ditekan?",
  SENSING_MOUSEDOWN: "mouse ditekan?",
  SENSING_MOUSEX: "x mouse",
  SENSING_MOUSEY: "y mouse",
  SENSING_SETDRAGMODE: "atur mode seret %1",
  SENSING_SETDRAGMODE_DRAGGABLE: "dapat diseret",
  SENSING_SETDRAGMODE_NOTDRAGGABLE: "tidak dapat diseret",
  SENSING_LOUDNESS: "kenyaringan",
  SENSING_LOUD: "nyaring?",
  SENSING_TIMER: "pengatur waktu",
  SENSING_RESETTIMER: "atur ulang pengatur waktu",
  SENSING_OF: "%1 dari %2",
  SENSING_OF_XPOSITION: "posisi x",
  SENSING_OF_YPOSITION: "posisi y",
  SENSING_OF_DIRECTION: "arah",
  SENSING_OF_COSTUMENUMBER: "# kostum",
  SENSING_OF_COSTUMENAME: "nama kostum",
  SENSING_OF_SIZE: "ukuran",
  SENSING_OF_VOLUME: "volume",
  SENSING_OF_BACKDROPNUMBER: "latar #",
  SENSING_OF_BACKDROPNAME: "nama latar",
  SENSING_OF_STAGE: "Panggung",
  SENSING_CURRENT: "%1 saat ini",
  SENSING_CURRENT_YEAR: "tahun",
  SENSING_CURRENT_MONTH: "bulan",
  SENSING_CURRENT_DATE: "tanggal",
  SENSING_CURRENT_DAYOFWEEK: "nama hari",
  SENSING_CURRENT_HOUR: "jam",
  SENSING_CURRENT_MINUTE: "menit",
  SENSING_CURRENT_SECOND: "detik",
  SENSING_DAYSSINCE2000: "hari-hari sejak 2000",
  SENSING_USERNAME: "nama pengguna",
  SENSING_USERID: "id pengguna",
  SOUND_PLAY: "mulai suara %1",
  SOUND_PLAYUNTILDONE: "mainkan suara %1 sampai selesai",
  SOUND_STOPALLSOUNDS: "hentikan semua suara",
  SOUND_SETEFFECTO: "atur efek %1 ke %2",
  SOUND_CHANGEEFFECTBY: "ubah efek %1 sebesar %2",
  SOUND_CLEAREFFECTS: "hapus semua efek suara",
  SOUND_EFFECTS_PITCH: "nada",
  SOUND_EFFECTS_PAN: "pan kiri/kanan",
  SOUND_CHANGEVOLUMEBY: "ubah volume sebesar %1",
  SOUND_SETVOLUMETO: "atur volume ke %1%",
  SOUND_VOLUME: "volume",
  SOUND_RECORD: "rekam...",
  CATEGORY_MOTION: "Gerakan",
  CATEGORY_LOOKS: "Tampilan",
  CATEGORY_SOUND: "Suara",
  CATEGORY_EVENTS: "Kejadian",
  CATEGORY_CONTROL: "Kontrol",
  CATEGORY_SENSING: "Sensor",
  CATEGORY_OPERATORS: "Operator",
  CATEGORY_VARIABLES: "Variabel",
  CATEGORY_MYBLOCKS: "Balok Saya",
  DUPLICATE: "Gandakan",
  DELETE: "Hapus",
  ADD_COMMENT: "Tambahkan Komentar",
  REMOVE_COMMENT: "Hapus Komentar",
  DELETE_BLOCK: "Hapus Balok",
  DELETE_X_BLOCKS: "Hapus %1 Balok",
  DELETE_ALL_BLOCKS: "Hapus semua %1 balok?",
  CLEAN_UP: "Bersihkan Balok-Balok",
  HELP: "Bantuan",
  UNDO: "Batalkan",
  REDO: "Ulangi",
  EDIT_PROCEDURE: "Edit",
  SHOW_PROCEDURE_DEFINITION: "Pergi ke pengartian",
  WORKSPACE_COMMENT_DEFAULT_TEXT: "Katakan sesuatu...",
  COLOUR_HUE_LABEL: "Warna",
  COLOUR_SATURATION_LABEL: "Saturasi",
  COLOUR_BRIGHTNESS_LABEL: "Keterangan",
  CHANGE_VALUE_TITLE: "Ubah nilai:",
  RENAME_VARIABLE: "Namakan ulang variabel",
  RENAME_VARIABLE_TITLE: 'Namakan ulang semua variabel "%1" ke:',
  RENAME_VARIABLE_MODAL_TITLE: "Namakan Ulang Variabel",
  NEW_VARIABLE: "Buat sebuah Variabel",
  NEW_VARIABLE_TITLE: "Nama variabel baru:",
  VARIABLE_MODAL_TITLE: "Variabel Baru",
  VARIABLE_ALREADY_EXISTS: 'Sebuah variabel bernama "%1" sudah ada.',
  VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE:
    'Sebuah variabel bernama "%1" sudah ada untuk variabel lain berjenis "%2".',
  DELETE_VARIABLE_CONFIRMATION: 'Hapus penggunaan %1 dari variabel "%2"?',
  CANNOT_DELETE_VARIABLE_PROCEDURE:
    'Tidak bisa menghapus variabel "%1" karena bagian dari pengartian fungsi "%2"',
  DELETE_VARIABLE: 'Hapus variabel "%1"',
  NEW_PROCEDURE: "Buat sebuah Balok",
  PROCEDURE_ALREADY_EXISTS: 'Sebuah prosedur bernama "%1" sudah ada',
  PROCEDURE_DEFAULT_NAME: "nama balok",
  PROCEDURE_USED:
    "Untuk menghapus sebuah definisi balok, pertama hapus semua penggunaan balok tersebut",
  NEW_LIST: "Buat sebuah Daftar",
  NEW_LIST_TITLE: "Nama daftar baru:",
  LIST_MODAL_TITLE: "Daftar Baru",
  LIST_ALREADY_EXISTS: 'Sebuah daftar bernama "%1" sudah ada.',
  RENAME_LIST_TITLE: 'Namakan ulang semua daftar "%1" ke:',
  RENAME_LIST_MODAL_TITLE: "Namakan Ulang Daftar:",
  DEFAULT_LIST_ITEM: "benda",
  DELETE_LIST: 'Hapus daftar "%1"',
  RENAME_LIST: "Namakan ulang daftar",
  NEW_BROADCAST_MESSAGE: "Pesan baru",
  NEW_BROADCAST_MESSAGE_TITLE: "Nama pesan baru:",
  BROADCAST_MODAL_TITLE: "Pesan Baru",
  DEFAULT_BROADCAST_MESSAGE_NAME: "pesan1",
};

// End of combined translations
